/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2025-09-11 02:55:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insertForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("insertForm.jsp\r\n");
      out.write("<br>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(function(){\r\n");
      out.write("		// alert(1);\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	function check(){\r\n");
      out.write("		if($('input[name=title]').val()==''){\r\n");
      out.write("            alert(\"제목을 입력해주세요.\")\r\n");
      out.write("            $('input[name=title]').focus();\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("		if ($('input[name=\"author\"]').val().trim() == \"\") {\r\n");
      out.write("	        alert(\"작가 누락\"); \r\n");
      out.write("	        $('input[name=\"author\"]').focus();\r\n");
      out.write("	        return false;\r\n");
      out.write("	     }\r\n");
      out.write("		if ($('input[name=\"publisher\"]').val().trim() == \"\") {\r\n");
      out.write("	        alert(\"publisher 누락\"); \r\n");
      out.write("	        $('input[name=\"publisher\"]').focus();\r\n");
      out.write("	        return false;\r\n");
      out.write("	    }\r\n");
      out.write("		if ($('input[name=\"price\"]').val().trim() == \"\") {\r\n");
      out.write("	        alert(\"price 누락\"); \r\n");
      out.write("	        $('input[name=\"price\"]').focus();\r\n");
      out.write("	        return false;\r\n");
      out.write("	    }\r\n");
      out.write("		if(isNaN($('input[name=price]').val())){ \r\n");
      out.write("            alert('가격은 숫자로 입력해주세요.');\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("		if ($('input[name=\"date\"]').val().trim() == \"\") {\r\n");
      out.write("	        alert(\"date 누락\"); \r\n");
      out.write("	        $('input[name=\"date\"]').focus();\r\n");
      out.write("	        return false;\r\n");
      out.write("	    }\r\n");
      out.write("		\r\n");
      out.write("		//if(!$('input[name=kind]').is(\":checked\")){\r\n");
      out.write("		if ($('input[name=\"kind\"]:checked').length == 0) {\r\n");
      out.write("            alert(\"배송비를 선택해주세요.\")\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("		\r\n");
      out.write("		if($('input[name=bookstore]:checked').length == 0) {\r\n");
      out.write("            alert(\"구입 가능 서점을 한 곳 이상 선택하세요\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("		//if($('select[name=count]').val() == '') {\r\n");
      out.write("		if($('select option:selected').val() == \"\"){\r\n");
      out.write("		    alert(\"수량을 선택하세요\");\r\n");
      out.write("		    return false;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("		\r\n");
      out.write("</script>\r\n");

	String[] bookstore = {"교보문고", "알라딘", "yes24", "인터파크"};
	String[] kind = {"유료", "무료"};

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1>도서 정보 입력</h1>\r\n");
      out.write("<form name=\"myform\" action=\"insertProc.jsp\" method=\"post\">\r\n");
      out.write("	<table border=1>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>제목</td>\r\n");
      out.write("			<td><input type=\"text\" name=\"title\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>저자</td>\r\n");
      out.write("			<td><input type=\"text\" name=\"author\">\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>출판사</td>\r\n");
      out.write("			<td><input type=\"text\" name=\"publisher\">\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>가격</td>\r\n");
      out.write("			<td><input type=\"text\" name=\"price\">\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>입고일</td>\r\n");
      out.write("			<td><input type=\"date\" name=\"day\">\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>배송비</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<!-- 유료 <input type=\"radio\" name=\"kind\" value=\"유료\"> \r\n");
      out.write("				무료	<input	type=\"radio\" name=\"kind\" value=\"무료\"> -->\r\n");
      out.write("				");

					for(int i=0;i<kind.length;i+=1){
				
      out.write("\r\n");
      out.write("					");
      out.print( kind[i] );
      out.write("<input type=\"radio\" name=\"kind\" value=\"");
      out.print( kind[i] );
      out.write("\">\r\n");
      out.write("				");

					};
				
      out.write("\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>구입가능 서점</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<!-- 교보문고 <input type=\"checkbox\" name=\"bookstore\" value=\"kyobo\">\r\n");
      out.write("				알라딘 <input type=\"checkbox\" name=\"bookstore\" value=\"aladin\">\r\n");
      out.write("				yes24 <input type=\"checkbox\" name=\"bookstore\" value=\"yes24\">\r\n");
      out.write("				인터파크 <input type=\"checkbox\" name=\"bookstore\" value=\"interpark\"> -->\r\n");
      out.write("				\r\n");
      out.write("				");

					for(int i=0;i<bookstore.length;i+=1){
				
      out.write("\r\n");
      out.write("					");
      out.print( bookstore[i] );
      out.write(" <input type=\"checkbox\" name=\"bookstore\" value=\"");
      out.print( bookstore[i] );
      out.write("\">\r\n");
      out.write("				");
 		
					}
				
      out.write("\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>보유수량</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<select name=\"count\">\r\n");
      out.write("					<option value=\"\">선택\r\n");
      out.write("					<!-- \r\n");
      out.write("					<option value=\"1\">1\r\n");
      out.write("					<option value=\"2\">2\r\n");
      out.write("					<option value=\"3\">3\r\n");
      out.write("					<option value=\"4\">4\r\n");
      out.write("					<option value=\"5\">5\r\n");
      out.write("					-->\r\n");
      out.write("				");

					for(int i=1; i<=5; i+=1){
				
      out.write("\r\n");
      out.write("					<option value=\"");
      out.print( i );
      out.write('"');
      out.write('>');
      out.print( i );
      out.write("\r\n");
      out.write("				");

					}
				
      out.write("\r\n");
      out.write("				</select>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("	</table>\r\n");
      out.write("	<br> <input type=\"submit\" value=\"전송\" onClick=\"return check()\"> \r\n");
      out.write("		<input type=\"reset\" value=\"취소\">\r\n");
      out.write("</form>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
