/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2025-09-12 05:18:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import myPkg.*;

public final class updateForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("myPkg");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      myPkg.MovieDao mdao = null;
      mdao = (myPkg.MovieDao) _jspx_page_context.getAttribute("mdao", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (mdao == null){
        mdao = new myPkg.MovieDao();
        _jspx_page_context.setAttribute("mdao", mdao, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');

	String num = request.getParameter("num");
	MovieBean mb = mdao.getMovieByNum(num);

      out.write("\r\n");
      out.write("\r\n");
 
	String [] genre = {"공포", "다큐", "액션", "애니메이션"};
	String [] time = {"08~10","10~12","12~14","14~16","16~18"};

      out.write("\r\n");
      out.write("\r\n");
      out.write("	<h2>영화 선호도 조사 수정 </h2>\r\n");
      out.write("	<form action=\"updateProc.jsp\" method=\"post\">\r\n");
      out.write("	\r\n");
      out.write("		<!-- form안에 input이 있어야 받은 num이 넘어감 -->\r\n");
      out.write("		<input type=\"hidden\" name=\"num\" value=\"");
      out.print(num );
      out.write("\">\r\n");
      out.write("		<table border=\"1\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>아이디</td>\r\n");
      out.write("			<td><input type=\"text\" name=\"id\" value=\"");
      out.print( mb.getId() );
      out.write("\"></td>  \r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>이름</td><td> \r\n");
      out.write("			<input type=\"text\" name=\"name\" value=\"");
      out.print( mb.getName() );
      out.write("\"></td> \r\n");
      out.write("		</tr> \r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>나이</td>\r\n");
      out.write("			<td><input type=\"text\" name=\"age\" value=\"");
      out.print( mb.getAge() );
      out.write("\"></td> \r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>좋아하는 장르</td>\r\n");
      out.write("			<td>\r\n");
      out.write("			");
for(String g : genre) { 
      out.write("\r\n");
      out.write("            	<input type=\"checkbox\" name=\"genre\" value=\"");
      out.print( g );
      out.write('"');
      out.write(' ');
if(mb.getGenre().contains(g)){ 
      out.write(" checked ");
}
      out.write(' ');
      out.write('>');
      out.print( g );
      out.write("         \r\n");
      out.write("			");
} 
      out.write("\r\n");
      out.write("				\r\n");
      out.write("			</td> \r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>즐겨보는 시간대</td>\r\n");
      out.write("			<td>\r\n");
      out.write("		\r\n");
      out.write("				<select name=\"time\">\r\n");
      out.write("					");
for(int i=0; i<time.length; i++){ 
      out.write("\r\n");
      out.write("					    <option value=\"");
      out.print(time[i] );
      out.write('"');
      out.write(' ');
if(mb.getTime().equals(time[i])){
      out.write(" selected ");
} 
      out.write('>');
      out.print(time[i] );
      out.write("</option>\r\n");
      out.write("\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("				</select>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>동반 관객수</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				");

				for(int i=1;i<=5;i++){
				
      out.write("\r\n");
      out.write("					<input type=\"radio\" name=\"partner\" value=\"");
      out.print(i);
      out.write('"');
      out.write(' ');
if(mb.getPartner()==i){ 
      out.write(" checked ");
}
      out.write('>');
      out.print(i);
      out.write("\r\n");
      out.write("				");
} 
      out.write("\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>영화관 개선사항</td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<textarea name=\"memo\" cols=\"40\" rows=\"3\">");
      out.print( mb.getMemo() );
      out.write("</textarea> \r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr align=\"center\">\r\n");
      out.write("			<td colspan=\"2\">\r\n");
      out.write("				<input type=\"submit\" value=\"수정하기\">\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
